global class ChangedDeleted {
    public String hello() {
        return 'Hello FeatureSkibbap!';
    }

    public String hello2() {
        return 'Hello FeatureSkibba2p!';
    }

    public String hello3() {
        return 'Hello FeatureSkibbap3!';
    }

    public String hello4() {
        return 'Hello FeatureSkibbap4!';
    }

    public String hello5() {
        return 'Hello FeatureSkibbap5!';
    }
}
