global class ChangedDeleted {
    public String hello() {
        return 'Hello EnvironmentSkibbap1!';
    }


    public String hello2() {
        return 'Hello EnvironmentSkibbap2!';
    }
    public String hello3() {
        return 'Hello EnvironmentSkibbap3!';
    }
    public String hello4() {
        return 'Hello EnvironmentSkibbap4!';
    }
    public String hello5() {
        return 'Hello EnvironmentSkibbap5!';
    }
}
